apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: korba-proxy-tls
spec:
  secretName: korba-proxy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: korba-proxy.powerwatch.io
  dnsNames:
  - korba-proxy.powerwatch.io
  acme:
    config:
    - http01:
        ingress: korba-proxy
      domains:
      - korba-proxy.powerwatch.io
